"""empty message

Revision ID: 25bb96674d8e
Revises: 8a5ee42497ba
Create Date: 2018-11-09 02:14:35.464416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25bb96674d8e'
down_revision = '8a5ee42497ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('user_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'user_name')
    # ### end Alembic commands ###
