"""empty message

Revision ID: 94c2ab4e6134
Revises: 25bb96674d8e
Create Date: 2018-11-09 02:23:53.752747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94c2ab4e6134'
down_revision = '25bb96674d8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('creator', sa.String(), nullable=True))
    op.drop_column('comments', 'user_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('user_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('comments', 'creator')
    # ### end Alembic commands ###
